[database]
server = "localhost"
port = "5432"
name = "ark-user"
user = "postgres"
password = "ZainToped"
provider = "postgres"

[mongo]
server = "localhost"
port =27017
user = "root"
password = "root"

[mq]
server = "localhost"
port = 5672
user = "root"
password = "root"